<a href="https://colab.research.google.com/github/veeranna-spec/ADM_27/blob/main/Lab_2_1390.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
a=pd.Series([6,9,1,3,4,5])
print(a)
d1=pd.Series([3,4,5,6,7,8])
s=pd.Series([4,3,2,6,7,4,5])
print(d1)
print(s)

0    6
1    9
2    1
3    3
4    4
5    5
dtype: int64
0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64
0    4
1    3
2    2
3    6
4    7
5    4
6    5
dtype: int64
0   -1.0
1    1.0
2    3.0
3    0.0
4    0.0
5    4.0
6    NaN
dtype: float64

In [ ]:
print(d1+s)
print(d1*s)
print(d1-s)

0     7.0
1     7.0
2     7.0
3    12.0
4    14.0
5    12.0
6     NaN
dtype: float64
0    12.0
1    12.0
2    10.0
3    36.0
4    49.0
5    32.0
6     NaN
dtype: float64
0   -1.0
1    1.0
2    3.0
3    0.0
4    0.0
5    4.0
6    NaN
dtype: float64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#with open('banklist.csv', 'r') as file:
    #content = file.read()
#print(content)
content=pd.read_csv('banklist.csv')
print(content)

                                             Bank Name                City  \
0                                  Fayette County Bank          Saint Elmo
1    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
2                                       First NBC Bank         New Orleans
3                                        Proficio Bank  Cottonwood Heights
4                        Seaway Bank and Trust Company             Chicago
..                                                 ...                 ...
548                                 Superior Bank, FSB            Hinsdale
549                                Malta National Bank               Malta
550                    First Alliance Bank & Trust Co.          Manchester
551                  National State Bank of Metropolis          Metropolis
552                                   Bank of Honolulu            Honolulu

     ST   CERT                Acquiring Institution Closing Date Updated Date
0    IL   1802            United Fidelity Bank, fsb    26-May-17    26-Jul-17
1    WI  30003  First-Citizens Bank & Trust Company     5-May-17    26-Jul-17
2    LA  58302                         Whitney Bank    28-Apr-17    26-Jul-17
3    UT  35495                    Cache Valley Bank     3-Mar-17    18-May-17
4    IL  19328                  State Bank of Texas    27-Jan-17    18-May-17
..   ..    ...                                  ...          ...          ...
548  IL  32646                Superior Federal, FSB    27-Jul-01    19-Aug-14
549  OH   6629                    North Valley Bank     3-May-01    18-Nov-02
550  NH  34264  Southern New Hampshire Bank & Trust     2-Feb-01    18-Feb-03
551  IL   3815              Banterra Bank of Marion    14-Dec-00    17-Mar-05
552  HI  21029                   Bank of the Orient    13-Oct-00    17-Mar-05

[553 rows x 7 columns]

In [ ]:
content.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

In [ ]:
uploaded=files.upload()

Saving banklist.csv to banklist.csv

In [ ]:
data=pd.read_csv('banklist.csv')
print(data)

                                             Bank Name                City  \
0                                  Fayette County Bank          Saint Elmo
1    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
2                                       First NBC Bank         New Orleans
3                                        Proficio Bank  Cottonwood Heights
4                        Seaway Bank and Trust Company             Chicago
..                                                 ...                 ...
548                                 Superior Bank, FSB            Hinsdale
549                                Malta National Bank               Malta
550                    First Alliance Bank & Trust Co.          Manchester
551                  National State Bank of Metropolis          Metropolis
552                                   Bank of Honolulu            Honolulu

     ST   CERT                Acquiring Institution Closing Date Updated Date
0    IL   1802            United Fidelity Bank, fsb    26-May-17    26-Jul-17
1    WI  30003  First-Citizens Bank & Trust Company     5-May-17    26-Jul-17
2    LA  58302                         Whitney Bank    28-Apr-17    26-Jul-17
3    UT  35495                    Cache Valley Bank     3-Mar-17    18-May-17
4    IL  19328                  State Bank of Texas    27-Jan-17    18-May-17
..   ..    ...                                  ...          ...          ...
548  IL  32646                Superior Federal, FSB    27-Jul-01    19-Aug-14
549  OH   6629                    North Valley Bank     3-May-01    18-Nov-02
550  NH  34264  Southern New Hampshire Bank & Trust     2-Feb-01    18-Feb-03
551  IL   3815              Banterra Bank of Marion    14-Dec-00    17-Mar-05
552  HI  21029                   Bank of the Orient    13-Oct-00    17-Mar-05

[553 rows x 7 columns]

In [ ]:
print(data.isnull().sum())

Bank Name                0
City                     0
ST                       0
CERT                     0
Acquiring Institution    0
Closing Date             0
Updated Date             0
dtype: int64

In [ ]:
data=pd.read_csv('titanic.csv')
print(data.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Handle missing values (impute with mean, median, or mode)
data['Age'].fillna(data['Age'].mean(), inplace=True) # Impute with mean
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True) # Impute

<ipython-input-33-44b6b4f8f10a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(), inplace=True) # Impute with mean
<ipython-input-33-44b6b4f8f10a>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True) # Impute

In [ ]:
print("\nMissing values after imputation:")
print(data.isnull().sum())

Missing values after imputation:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [ ]:
!pip install scikit-learn  # Install scikit-learn if you haven't already
from sklearn.preprocessing import MinMaxScaler # Import MinMaxScaler

scaler_minmax = MinMaxScaler()
columns_to_normalize = ['Age', 'Fare']
data[columns_to_normalize] = scaler_minmax.fit_transform(data[columns_to_normalize])

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)

In [ ]:
# Import StandardScaler from sklearn.preprocessing
from sklearn.preprocessing import StandardScaler

scaler_standard = StandardScaler()
data[columns_to_normalize] = scaler_standard.fit_transform(data[columns_to_normalize])

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.592481,1,0,A/5 21171,-0.502445,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.638789,1,0,PC 17599,0.786845,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.284663,0,0,STON/O2. 3101282,-0.488854,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.407926,1,0,113803,0.420730,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,0.407926,0,0,373450,-0.486337,NaN,S